#!/usr/bin/env node
// Build js/data/paper_shelf.js — curated papers/memos shelf extracted verbatim
// from the NotebookLM captures AND from locally downloaded PDFs.
// Every entry carries its source file + sha256 (capture JSON or original PDF).
// Honesty rules: no fabricated answers; image-only sources are summary-level;
// parse failures fall back to raw verbatim text; scanned PDFs open the
// original file byte-for-byte (mode "pdf") instead of inventing text.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { classifyLocalFile, resolveLocalPairs } from "./paper_naming.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CAP_DIR = path.join(ROOT, "research", "captures", "notebooklm_sources");
const LOCAL_CAP_DIR = path.join(ROOT, "research", "captures", "local_pdfs");
const DATA_DIR = path.join(ROOT, "research", "Data-QuestionPapers-and-Memos-Downloaded");
const OUT = path.join(ROOT, "js", "data", "paper_shelf.js");

const manifest = JSON.parse(fs.readFileSync(path.join(CAP_DIR, "manifest.json"), "utf8"));
const captureByPrefix = new Map();
for (const nb of manifest.notebooks) {
  captureByPrefix.set(nb.file.slice(0, 2), { file: nb.file, sha256: nb.sha256, record: JSON.parse(fs.readFileSync(path.join(CAP_DIR, nb.file), "utf8")) });
}

// Locally downloaded source PDFs: manifest hashes the ORIGINAL file; extracted
// text lives beside it in research/captures/local_pdfs/.
const localManifest = JSON.parse(fs.readFileSync(path.join(LOCAL_CAP_DIR, "manifest.json"), "utf8"));
const localByPath = new Map(localManifest.files.map((entry) => [entry.file, entry]));
// Shelf build date = when the folder was last measured (regenerated by
// scripts/extract_local_text.py), not a hand-edited constant.
const BUILT_ON = localManifest.builtOn || new Date().toISOString().slice(0, 10);

// Phase 2 OCR: scripts/ocr_papers.py transcribes scanned originals with two
// independent engines (Windows.Media.Ocr + rapidocr-onnxruntime) and records
// agreement per file. MEASURED calibration vs native text layers (see
// ocr_manifest.json): rapidocr cbigram f1 0.920-0.969, Windows OCR 0.906-0.948;
// rapidocr also keeps table rows in reading order where Windows OCR column-
// groups them, so the RAPID text is what the parser consumes and Windows OCR
// is the independent cross-check. Policy: a transcription only enters the
// bank when the engines agree on character content (cbigramF1 >= 0.85,
// spacing-invariant) AND on digit runs (digitRunF1 >= 0.80 — marks, values,
// codes). Failures stay pdf-mode entries that open the original file.
const OCR_MANIFEST_PATH = path.join(LOCAL_CAP_DIR, "ocr_manifest.json");
const ocrManifest = fs.existsSync(OCR_MANIFEST_PATH)
  ? JSON.parse(fs.readFileSync(OCR_MANIFEST_PATH, "utf8"))
  : { files: [], engines: { primary: "windows-media-ocr (en-GB, system)", cross: "rapidocr-onnxruntime" } };
const ocrByFile = new Map(ocrManifest.files.map((entry) => [entry.file, entry]));
const OCR_MIN_CBIGRAM = 0.85;
const OCR_MIN_DIGITRUN = 0.8;

function ocrGate(entry) {
  if (!entry || entry.error || !entry.winrtFile || !entry.rapidFile) return false;
  return entry.cbigramF1 >= OCR_MIN_CBIGRAM && entry.digitRunF1 >= OCR_MIN_DIGITRUN;
}

function sha256File(absPath) {
  return crypto.createHash("sha256").update(fs.readFileSync(absPath)).digest("hex");
}

function findLocal(c) {
  const rel = `research/Data-QuestionPapers-and-Memos-Downloaded/${c.file}`;
  const record = localByPath.get(rel);
  if (!record) throw new Error(`local source not in manifest: ${rel}`);
  const actual = sha256File(path.join(ROOT, rel));
  if (actual.toUpperCase() !== record.sha256.toUpperCase()) throw new Error(`local sha mismatch: ${rel}`);
  return { rel, record };
}

function findSource(prefix, name) {
  const cap = captureByPrefix.get(prefix);
  if (!cap) throw new Error(`capture ${prefix} not found`);
  const src = cap.record.sources.find((s) => s.name === name);
  if (!src) throw new Error(`source not found in ${prefix}: ${name}`);
  return { cap, src };
}

// ---------- capture hygiene: document footers/headers + formula sheet ----------
//
// PDF two-column extraction bleeds page furniture (department headers, marking-
// guideline footers, page numbers, "TOTAL: 100" strips) into neighbouring rows.
// These patterns delete that furniture from parsed rows only — never from raw
// or image-summary modes, and never from question content.

// The real sheet starts at "FORMULA SHEET <n> $…"; the cover-page sentence
// "…formula sheet." never has maths after it, so it cannot match.
const FORMULA_SHEET_START = /FORMULA SHEET\s*\d*\s*\$/i;
const FORMULA_SHEET_END =
  /higher education & training|Department: Higher Education|This marking guideline|MARKING GUIDELINE|Regional Assessment|\bPage \d+ of \d+\b/i;

const BOILER_PATTERNS = [
  // cover-page sentence "…formula sheet." is never a real sheet (marker needs $)
  /\bThis marking guideline consists of \d+ pages?\./gi,
  /\bMEMORANDUM\s*\/\s*MARKING GUIDELINES?\b/gi,
  /MARKING GUIDELINE(?:\s*-\s*\d+\s*-\s*[A-Z][A-Z0-9 &]{2,40})?/gi,
  /Regi(?:onal|ortal)\s+Assessment\s*:?\s*\d{4}\s*\/\s*\d{2}\s*\/\s*\d{2}/gi,
  /\bRegional Assessment\s*:/gi,
  /\bRegional Assessment\b(?=\s+\d{4})/gi,
  /\bPage \d+ of \d+\b/gi,
  /\b\d{4}\/\d{2}\/\d{2}\b/g,
  // page-total strips: GRAND before SECTION (interleaved by two-column bleed).
  // Parens form ("GRAND TOTAL (30) 5") keeps a stray page digit behind it.
  /\bGRAND TOTAL(?:\s*\(\d+\)|:?\s*\d+)(?:\s+\d{1,3})?/gi,
  /\bTOTAL SECTION [A-Z]:?\s*\d*/gi,
  /\bTOTAL MARKS\b/gi,
  /\[\d{1,3}\]\s*TOTAL:\s*\d+/gi,
  /\bTOTAL:\s*\d+(?:\s+MARKS)?/gi,
  /\bSECTION [A-Z]\s*$/g, // trailing paper-structure heading
  /\bANN?EXURE [A-Z] ANSWER SHEET\b/gi,
  /\bEXAMINATION NUMBER\s*:/gi,
  /\bADDENDUM\s*$/g, // addendum page heading after its form fields
  /\bhigher education & training\b/gi,
  /\bDepartment: Higher Education and Training\b/gi,
  /\bREPUBLIC OF SOUTH AFRICA(?: GOVERNMENT)?(?: KZN REGIONAL OFFICE)?\b/g,
  /\bNATIONAL CERTIFICATE \(VOCATIONAL\)/g,
  /\bFUNDAMENTALS MATHEMATICS NQF LEVEL\s*:?\s*\d/g,
  /\bNQF LEVEL\s*:?\s*\d\b/g,
  /\bTASK\s*:\s*\d{1,2}\b/g,
  /\bDATE\s*:\s*\d{1,2}\s+[A-Za-z]+\s+\d{4}\b/g,
  /\bMARKS\s*:\s*\d{1,3}\b/g,
  /\bXX March \d{4}\b/g,
  // paper codes (NC1520(E)(M1)V) and subject codes ((10040052), (6030092)…)
  /\bNC\d{3,4}\([A-Z]\)\([A-Z]\d{1,2}\)V\b/g,
  /\(\d{7,8}\)/g,
  /(?<=\s)-\d{1,2}-(?=\s|$)/g,
];

function stripBoilerplate(normalized) {
  let out = normalized;
  const sheet = FORMULA_SHEET_START.exec(out);
  if (sheet) {
    const from = sheet.index + sheet[0].length - 1; // keep the opening "$"
    const end = FORMULA_SHEET_END.exec(out.slice(from));
    const cut = end ? from + end.index : out.length;
    out = out.slice(0, sheet.index) + " " + out.slice(cut);
  }
  for (const pattern of BOILER_PATTERNS) out = out.replace(pattern, " ");
  return out.replace(/\s+/g, " ").trim();
}

// Pull the captured FORMULA SHEET formulas out verbatim so stripping the
// furniture from question rows never loses the maths itself.
function extractFormulaSheet(text) {
  const start = FORMULA_SHEET_START.exec(text);
  if (!start) return null;
  const from = start.index + start[0].length - 1;
  const end = FORMULA_SHEET_END.exec(text.slice(from));
  const region = text.slice(from, end ? from + end.index : text.length);
  const formulas = region.match(/\$[^$\n]+\$/g) || [];
  return formulas.length > 0 ? formulas : null;
}

// ---------- parsers ----------

const SUB_ANCHOR = /(?:^|[\s|])(\d{1,2}\.\d{1,2}(?:\.\d{1,2})?)(?=[\s:])/g;
const MARKS_TAIL = /\((\d{1,3}(?:\s*[x\u00d7X]\s*\d{1,3})?)\)\s*$/;

function anchorOk(n) {
  const [a, b] = n.split(".").map(Number);
  if (!(a >= 1 && a <= 30 && b >= 1 && b <= 19)) return false;
  if (n.split(".").length === 3) {
    const c = Number(n.split(".")[2]);
    if (!(c >= 1 && c <= 19)) return false;
  }
  return true;
}

const GROUP_TAIL = /\((\d+)\s*[x\u00d7]\s*(\d+)\)\s*\((\d+)\)\s*$/;

// Papers print "(2 × 2) (4)" once after the LAST sub of a group when no
// individual marks are shown — that is the group total, not this sub's marks.
// Detect: product matches and the multiplier equals the group's sub count.
function isGroupTotalTail(n, anchors, text) {
  const m = text.match(GROUP_TAIL);
  if (!m) return false;
  if (Number(m[1]) * Number(m[2]) !== Number(m[3])) return false;
  const dot = n.lastIndexOf(".");
  if (dot < 0) return false;
  const prefix = n.slice(0, dot + 1);
  const siblings = anchors.filter((x) => x.n.startsWith(prefix) && x.n.length > prefix.length).length;
  return siblings === Number(m[1]);
}

function parseAnchorSubs(block) {
  const anchors = [];
  SUB_ANCHOR.lastIndex = 0;
  let m;
  while ((m = SUB_ANCHOR.exec(block)) !== null) {
    const n = m[1];
    if (!anchorOk(n)) continue;
    const start = m.index + m[0].length - n.length;
    if (anchors.length && start <= anchors[anchors.length - 1].start) continue;
    anchors.push({ n, start });
  }
  const subs = [];
  for (let i = 0; i < anchors.length; i++) {
    const a = anchors[i];
    const end = i + 1 < anchors.length ? anchors[i + 1].start : block.length;
    let text = block.slice(a.start, end);
    // drop the row's own number label when it prefixes the text
    if (text.startsWith(a.n) && (text.length === a.n.length || !/[0-9]/.test(text[a.n.length]))) {
      text = text.slice(a.n.length).replace(/^[\s:]+/, "");
    }
    text = stripBoilerplate(text.replace(/\s+/g, " ").trim());
    let marks = null;
    if (!isGroupTotalTail(a.n, anchors, text)) {
      const mm = text.match(MARKS_TAIL);
      if (mm) {
        marks = mm[1].replace(/\s+/g, "");
        text = text.slice(0, text.length - mm[0].length);
      }
    }
    text = text.replace(/\s+/g, " ").trim();
    if (text.length > 0 && text.length < 3) continue;
    subs.push({ n: a.n, text, marks, ...(text.length === 0 ? { empty: true } : {}) });
  }
  subs.sort((x, y) => {
    const p = (s) => s.n.split(".").map(Number);
    const a = p(x), b = p(y);
    for (let i = 0; i < 3; i++) if ((a[i] || 0) !== (b[i] || 0)) return (a[i] || 0) - (b[i] || 0);
    return 0;
  });
  return { subs, firstStart: anchors.length ? anchors[0].start : -1 };
}

// Page-banner words a header may legally sit behind on the same line
// ("Downloaded from TVET NCV Exam Papers\nQUESTION 2" can lose its newline).
const BANNER_PREV = new Set(["papers", "guides", "study", "exam", "app", "room", "down"]);

// Real headers sit at a line start; in-sentence cross-references ("circuit A
// in QUESTION 2", "mentioned in QUESTION 4.1") are NOT block starts and must
// not truncate the question they appear inside.
const REF_PREPOSITIONS = new Set([
  "in", "of", "to", "from", "see", "after", "before", "within", "under",
  "between", "and", "or", "for", "on", "at", "is", "are", "that", "this",
]);

// Spacing-insensitive character-bigram F1 (mirrors agreement() in
// ocr_papers.py) — used to prove that the cross-check engine's text for an
// anchor is the SAME content before its better spacing is trusted.
function cbSim(a, b) {
  const grams = (s) => {
    const t = s.replace(/\s+/g, "").toLowerCase();
    const m = new Map();
    for (let i = 0; i + 1 < t.length; i++) {
      const g = t.slice(i, i + 2);
      m.set(g, (m.get(g) || 0) + 1);
    }
    return m;
  };
  const A = grams(a);
  const B = grams(b);
  if (!A.size || !B.size) return 0;
  let overlap = 0;
  let na = 0;
  let nb = 0;
  for (const c of A.values()) na += c;
  for (const c of B.values()) nb += c;
  for (const [g, c] of A) overlap += Math.min(c, B.get(g) || 0);
  return na + nb ? (2 * overlap) / (na + nb) : 0;
}

// The two OCR engines are complementary: rapidocr keeps table rows in reading
// order but sometimes glues words together ("Identifythecomponents"); Windows
// OCR spaces words correctly but column-groups tables. Where BOTH parsed the
// same anchor and their texts agree modulo spacing, take the cross-check's
// wording; otherwise keep the parsed engine's text untouched. Marks stay with
// the parse that produced them — a cross marks value is only adopted when the
// parse never saw a tail, and a tail the parse read as a group total is never
// reinterpreted.
function fillFromCross(parsed, cross) {
  const map = new Map();
  for (const q of cross.questions) {
    for (const s of q.subs) if (s.text && !s.empty) map.set(`${q.n}/${s.n}`, s);
  }
  // Only repair glue: take the cross text when our text still has a glued
  // run AND the cross text has none — never downgrade spaced text back into
  // the cross engine's own glued wording.
  const GLUED = /[a-z]{21,}/;
  let filled = 0;
  for (const q of parsed.questions) {
    for (const s of q.subs) {
      if (!s.text || s.empty) continue;
      if (!GLUED.test(s.text)) continue;
      const c = map.get(`${q.n}/${s.n}`);
      if (!c || GLUED.test(c.text) || cbSim(s.text, c.text) < 0.6) continue;
      const rapidTail = MARKS_TAIL.test(s.text);
      if (s.marks != null) {
        const mm = c.text.match(MARKS_TAIL);
        const text = mm ? c.text.slice(0, c.text.length - mm[0].length).trim() : c.text;
        if (text === s.text) continue;
        s.text = text;
        filled++;
      } else if (c.marks != null) {
        if (rapidTail) continue;
        s.marks = c.marks;
        s.text = c.text;
        filled++;
      } else if (c.text !== s.text) {
        s.text = c.text;
        filled++;
      }
    }
  }
  return filled;
}

function questionStarts(text, strict = false) {
  const starts = [];
  // \s* (not \s+): OCR linearsiers emit "QUESTION1" with no space after a
  // banner merge; real words never sit between QUESTION and the digit
  // ("QUESTIONS 2" is caught by the digit requirement anyway).
  const re = /\bQUESTION\s*(\d+)\b/gi;
  let m;
  while ((m = re.exec(text)) !== null) {
    const before = text.slice(Math.max(0, m.index - 14), m.index);
    const atLineStart = /(?:^|\n)\s*$/.test(before);
    const prevWord = (before.trim().match(/[A-Za-z]+$/) || [""])[0].toLowerCase();
    if (strict) {
      // OCR linearizations: spacing repair exposes mid-line cross-refs like
      // "saved as QUESTION 3" as matches — a header must be line-start or
      // directly behind a glued page banner, never inside a sentence.
      if (!atLineStart && !BANNER_PREV.has(prevWord)) continue;
    } else if (!atLineStart && REF_PREPOSITIONS.has(prevWord)) continue;
    starts.push(m);
  }
  return starts;
}

function parseQA(text, opts = {}) {
  const starts = questionStarts(text, !!opts.strictHeaders);
  if (starts.length === 0) return { questions: [], subs: 0, dupes: 0, embeddedMemo: 0 };
  const blocks = [];
  for (let i = 0; i < starts.length; i++) {
    const from = starts[i].index + starts[i][0].length;
    const to = i + 1 < starts.length ? starts[i + 1].index : text.length;
    blocks.push({ n: starts[i][1], block: text.slice(from, to) });
  }
  // group by question number; repeated markers are either column repeats or an
  // embedded memo (only trusted when opts.embeddedMemo is set on the source).
  const byN = new Map();
  for (const b of blocks) {
    if (!byN.has(b.n)) byN.set(b.n, []);
    byN.get(b.n).push(b.block);
  }
  const seen = new Set();
  let dupes = 0;
  let embeddedMemo = 0;
  const questions = [];
  for (const [n, blockList] of byN) {
    const { subs, firstStart } = parseAnchorSubs(blockList[0]);
    const kept = [];
    for (const s of subs) {
      if (seen.has(s.n)) { dupes++; continue; }
      seen.add(s.n);
      kept.push(s);
    }
    let stem = "";
    if (kept.length > 0 && firstStart > 0) {
      stem = stripBoilerplate(blockList[0].slice(0, firstStart).replace(/\s+/g, " ").trim());
      if (/^\W*\d/.test(stem)) stem = "";
    } else if (kept.length === 0) {
      stem = stripBoilerplate(blockList[0].replace(/\s+/g, " ").trim());
    }
    if (kept.length === 0 && stem.length < 30) continue;
    if (opts.embeddedMemo && blockList.length > 1) {
      const memoMap = new Map(parseAnchorSubs(blockList[1]).subs.filter((s) => !s.empty).map((s) => [s.n, s.text]));
      for (const s of kept) {
        if (memoMap.has(s.n)) { s.memo = memoMap.get(s.n); embeddedMemo++; }
        else s.memo = null;
      }
    }
    questions.push({ n, stem, subs: kept });
  }
  const subs = questions.reduce((t, q) => t + q.subs.length, 0);
  return { questions, subs, dupes, embeddedMemo };
}

function parseSolutions(text) {
  const heads = [...text.matchAll(/QUESTION\s+(\d+\.\d+)\s*:/g)];
  if (heads.length < 3) return null;
  const blocks = [];
  for (let i = 0; i < heads.length; i++) {
    const from = heads[i].index + heads[i][0].length;
    const to = i + 1 < heads.length ? heads[i + 1].index : text.length;
    const seg = text.slice(from, to);
    const ansIdx = seg.search(/\bAnswer\s*:/i);
    const anaIdx = seg.search(/\bAnalysis\s*:/i);
    let question = seg;
    let answer = "";
    let analysis = "";
    if (ansIdx >= 0) {
      question = seg.slice(0, ansIdx);
      const ansEnd = anaIdx > ansIdx ? anaIdx : seg.length;
      answer = seg.slice(ansIdx + seg.slice(ansIdx).search(/:/) + 1, ansEnd);
      if (anaIdx > ansIdx) analysis = seg.slice(anaIdx + seg.slice(anaIdx).search(/:/) + 1);
    }
    const clean = (s) =>
      stripBoilerplate(
        s.replace(/\s+/g, " ").replace(/^[\s\u2022\u00b7\-–—]+/, "").replace(/[\s\u2022\u00b7]+$/, "").trim()
      );
    const entry = { n: heads[i][1], question: clean(question), answer: clean(answer), analysis: clean(analysis) };
    if (entry.question && entry.answer) blocks.push(entry);
  }
  return blocks.length >= 3 ? blocks : null;
}

function parseSolvedSets(text) {
  const qpIdx = [...text.matchAll(/Question Paper\s*:/gi)].map((m) => m.index);
  const memoIdx = [...text.matchAll(/Marking Memorandum/gi)].map((m) => m.index);
  if (qpIdx.length === 0 || memoIdx.length === 0) return null;
  const sets = [];
  for (let i = 0; i < qpIdx.length; i++) {
    const qpStart = qpIdx[i];
    const qpEnd = i + 1 < qpIdx.length ? qpIdx[i + 1] : text.length;
    const memoStart = memoIdx.find((x) => x >= qpStart && x < qpEnd);
    if (memoStart === undefined) continue;
    const label = text.slice(qpStart, Math.min(qpStart + 80, memoStart)).split("\n")[0].trim();
    const qpSubs = parseAnchorSubs(text.slice(qpStart, memoStart)).subs;
    const memoSubs = parseAnchorSubs(text.slice(memoStart, qpEnd)).subs;
    const memoMap = new Map(memoSubs.filter((s) => !s.empty).map((s) => [s.n, s]));
    const subs = qpSubs.map((s) => ({ ...s, memo: memoMap.has(s.n) ? memoMap.get(s.n).text : null }));
    if (subs.length > 0) sets.push({ label, subs });
  }
  return sets.length > 0 ? sets : null;
}

// ---------- curated inventory ----------

const CURATED = [
  // Introduction to Computer
  { id: "intro-2010-qp", prefix: "11", name: "NC1200 - INTRODUCTION TO COMPUTERS NOV QP 2010.pdf", subject: "introduction-to-computer", title: "NC1200 Introduction to Computers — November 2010", session: "November 2010", kind: "qp", level: "L2", mode: "qa" },
  { id: "intro-2018mar-qp", prefix: "11", name: "2018 MAR NC1520 - INTRODUCTION TO COMPUTERS L2 QP SUPP 2018.pdf", subject: "introduction-to-computer", title: "NC1520 Introduction to Computers — Supplementary 2018", session: "March 2018 (Supplementary)", kind: "qp", level: "L2", mode: "qa" },
  { id: "intro-2018nov-qp", prefix: "11", name: "2018 NOV NC1540 - INTRODUCTION TO COMPUTERS L2 QP NOV 2018 (amended).pdf", subject: "introduction-to-computer", title: "NC1540 Introduction to Computers — November 2018 (amended)", session: "November 2018", kind: "qp", level: "L2", mode: "qa" },
  { id: "intro-2021-qp", prefix: "11", name: "2021 MAR NC1540 - INTRODUCTION TO COMPUTERS L2 QP FEB 2021 REPLACEMENT SIGN OFF.pdf", subject: "introduction-to-computer", title: "NC1540 Introduction to Computers — February 2021 replacement", session: "February 2021 (Replacement)", kind: "qp", level: "L2", mode: "qa", pairId: "intro-2021-memo" },
  { id: "intro-2021-memo", prefix: "11", name: "2021 MAR NC1540 - INTRODUCTION TO COMPUTERS L2 MEMO FEB 2021 REPLACEMENT SIGN OFF.pdf", subject: "introduction-to-computer", title: "NC1540 Introduction to Computers — Feb 2021 memo", session: "February 2021 (Replacement)", kind: "memo", level: "L2", mode: "qa", pairId: "intro-2021-qp" },
  // Mathematics
  { id: "math-2015p1", prefix: "12", name: "MATHEMATICS_L2_NOVEMBER_2015_1ST_PAPER_PAPER_tvetpapers.co.za.pdf", subject: "mathematics", title: "Mathematics L2 — November 2015, Paper 1", session: "November 2015 · Paper 1", kind: "qp", level: "L2", mode: "images" },
  { id: "math-task1-2025", prefix: "12", name: "Maths-March-Paper.pdf", subject: "mathematics", title: "Mathematics L2 — KZN Regional Task 1", session: "KZN Regional Task 1 · 20 February 2025", kind: "qp", level: "L2", mode: "qa", embeddedMemo: true },
  { id: "math-task2-2026", prefix: "12", name: "Maths-NQF-L2-Task2V2.pdf", subject: "mathematics", title: "Mathematics L2 — Task 2(V1)", session: "Task 2(V1) · 18 March 2026", kind: "qp", level: "L2", mode: "qa" },
  { id: "math-exercize-memo", prefix: "12", name: "Math Exercize.pdf", subject: "mathematics", title: "Mathematics L2 — worked exercise memo", session: "worked assignment memo", kind: "solutions", level: "L2", mode: "solutions" },
  { id: "math-task6", prefix: "17", name: "MathsTask6(V1).pdf", subject: "mathematics", title: "Mathematics L2 — Task 6(V1)", session: "Task 6(V1) · 50 marks", kind: "qp", level: "L2", mode: "images" },
  // Electrotechnology
  { id: "elec-nc1000-qp-2023", prefix: "01", name: "NC1000_-_ELECTROTECHNOLOGY-L2-QP-NOV-2023_from_tvetpapers.co.za (1).pdf", subject: "electrotechnology", title: "NC1000 Electrotechnology — November 2023 QP", session: "November 2023", kind: "qp", level: "L2", mode: "images", pairId: "elec-nc1000-memo-2023" },
  { id: "elec-nc1000-memo-2023", prefix: "01", name: "NC1000_-_ELECTROTECHNOLOGY-L2-MEMO-NOV-2023_from_tvetpapers.co.za.pdf", subject: "electrotechnology", title: "NC1000 Electrotechnology — November 2023 memo", session: "November 2023", kind: "memo", level: "L2", mode: "images", pairId: "elec-nc1000-qp-2023" },
  { id: "elec-nc1000-memo-2022", prefix: "01", name: "NC1000 - ELECTROTECHNOLOGY L2 MEMO NOV 2022 EDITED.pdf", subject: "electrotechnology", title: "NC1000 Electrotechnology — November 2022 memo", session: "November 2022", kind: "memo", level: "L2", mode: "images" },
  { id: "elec-nc1000-memo-supp2023", prefix: "01", name: "NC1000 - ELECTROTECHNOLOGY L2 MEMO SUPP 2023 (1).pdf", subject: "electrotechnology", title: "NC1000 Electrotechnology — Supplementary 2023 memo", session: "Supplementary 2023", kind: "memo", level: "L2", mode: "images" },
  { id: "elec-2025y", prefix: "07", name: "Electrotechnology NQF Level 2 - November 2025 - Y-Paper.pdf", subject: "electrotechnology", title: "Electrotechnology L2 — November 2025 Y-paper", session: "21 November 2025 (Y-paper)", kind: "qp", level: "L2", mode: "images" },
  { id: "elec-calc-guide", prefix: "04", name: "Electrotechnology Test Calculation Study Guide", subject: "electrotechnology", title: "Electrotechnology — test calculation study guide (worked)", session: "worked calculation guide", kind: "solutions", level: "L2", mode: "raw" },
  { id: "elec-activity-solutions", prefix: "08", name: "Electrotech Activity Solutions and Questionnaire", subject: "electrotechnology", title: "Electrotechnology — activity solutions and questionnaire", session: "activity solutions", kind: "solutions", level: "L2", mode: "raw" },
  // Mechatronic Systems
  { id: "mech-nc2090-qp", prefix: "06", name: "NC2090 - MECHATRONIC SYSTEMS L2 QP SUPP 2019.pdf", subject: "mechatronic-systems", title: "NC2090 Mechatronic Systems — Supplementary 2019", session: "Supplementary 2019", kind: "qp", level: "L2", mode: "qa" },
  { id: "mech-nc2100-qp", prefix: "06", name: "NC2100 - MECHATRONIC SYSTEMS L3 QP SUPP 2019.pdf", subject: "mechatronic-systems", title: "NC2100 Mechatronic Systems — Supplementary 2019", session: "Supplementary 2019", kind: "qp", level: "L3", mode: "qa" },
  { id: "mech-june-test", prefix: "03", name: "Mechatronics June Practice Test Paper.pdf", subject: "mechatronic-systems", title: "Mechatronics — June practice test", session: "June practice test (year not stated)", kind: "practice", level: "L2", mode: "raw" },
  { id: "mech-q5-master", prefix: "03", name: "Advanced Mechatronics Study Guide: The Comprehensive Question 5 Master Series (Exam & Memorandum)", subject: "mechatronic-systems", title: "Mechatronics — Question 5 Master Series (exam & memorandum)", session: "practice exam + memorandum", kind: "solved", level: "L2", mode: "solved" },
  { id: "mech-pasted-practice", prefix: "06", name: "Pasted text", subject: "mechatronic-systems", title: "Mechatronics — March assessment practice set", session: "practice question set", kind: "practice", level: "L2", mode: "qa" },
  { id: "mech-gclamp", prefix: "05", name: "G Clamp Manufacturing Activity Questions", subject: "mechatronic-systems", title: "G-clamp manufacturing — activity with worked explanations", session: "class activity", kind: "solutions", level: "L2", mode: "qa" },
  { id: "mech-isat", prefix: "05", name: "ElectroAndIntro-ISAT.pdf", subject: "mechatronic-systems", title: "ISAT — electrotechnology & intro questionnaire", session: "ISAT questionnaire", kind: "practice", level: "L2", mode: "raw" },
  // Manual Manufacturing
  { id: "mm-nc1780-qp", prefix: "15", name: "NC1780 - MANUAL MANUFACTURING L2 QP NOV 2013 NEW.pdf", subject: "manual-manufacturing", title: "NC1780 Manual Manufacturing — November 2013", session: "November 2013", kind: "qp", level: "L2", mode: "qa" },
  { id: "mm-nc1810-qp-2019", prefix: "15", name: "NC1810 - MANUAL MANUFACTURING L2 QP SUPP 2019.pdf", subject: "manual-manufacturing", title: "NC1810 Manual Manufacturing — Supplementary 2019", session: "Supplementary 2019", kind: "qp", level: "L2", mode: "qa" },
  { id: "mm-qp-2025", prefix: "15", name: "NC1810_-_MANUAL_MANUFACTURING_L2_QP_FEB_2025_-_tvetpapers.co.za.pdf", subject: "manual-manufacturing", title: "NC1810 Manual Manufacturing — February 2025 QP", session: "February 2025", kind: "qp", level: "L2", mode: "images", pairId: "mm-memo-2025" },
  { id: "mm-memo-2025", prefix: "15", name: "NC1810_-_MANUAL_MANUFACTURING_L2_MEMO_FEB_2025_-_tvetpapers.co.za.pdf", subject: "manual-manufacturing", title: "NC1810 Manual Manufacturing — February 2025 memo", session: "February 2025", kind: "memo", level: "L2", mode: "images", pairId: "mm-qp-2025" },
  { id: "mm-qp-supp2024", prefix: "15", name: "NC1810_-_MANUAL_MANUFACTURING_L2_QP_SUPP_2024_from_tvetpapers.co.za.pdf", subject: "manual-manufacturing", title: "NC1810 Manual Manufacturing — Supplementary 2024 QP", session: "Supplementary 2024", kind: "qp", level: "L2", mode: "images", pairId: "mm-memo-supp2024" },
  { id: "mm-memo-supp2024", prefix: "15", name: "NC1810_-_MANUAL_MANUFACTURING_L2_MEMO_SUPP_2024_from_tvetpapers.co.za.pdf", subject: "manual-manufacturing", title: "NC1810 Manual Manufacturing — Supplementary 2024 memo", session: "Supplementary 2024", kind: "memo", level: "L2", mode: "images", pairId: "mm-qp-supp2024" },
];

// Locally downloaded QPs/memos (the user's own tvetpapers + NCV files).
// mode "qa"  = text layer extracted at build time (PDF or DOCX).
// mode "pdf" = scan only: reader opens the original file; nothing invented.
// Local downloads: classified from filenames (scripts/paper_naming.mjs) plus
// minimal catalog.json overrides for irregular names — one entry per
// manifest.json row, pairs derived from subject+session. No hand list to edit
// when a new year of papers is dropped into the folder.
const catalog = JSON.parse(fs.readFileSync(path.join(DATA_DIR, "catalog.json"), "utf8"));
const catalogByFile = new Map(catalog.overrides.map((o) => [o.file, o.overrides]));
const LOCAL = resolveLocalPairs(
  localManifest.files.map((entry) =>
    classifyLocalFile(path.basename(entry.file), catalogByFile.get(path.basename(entry.file)) || {}),
  ),
);

// ---------- build ----------

const shelf = [];
const stats = [];

// Formula sheet + shelf push + stats, shared by both source loops.
function pushEntry(c, entry, text) {
  // Keep the captured formula sheet verbatim: its rows are stripped out of the
  // question text above (page furniture), so the maths is preserved here.
  if (["qa", "solved", "solutions"].includes(entry.mode)) {
    const sheet = extractFormulaSheet(text);
    if (sheet) {
      entry.formulaSheet = sheet;
      entry.note += ` Captured FORMULA SHEET kept verbatim (${sheet.length} formulas) as its own block.`;
    }
  }
  shelf.push(entry);
  const stat = { id: c.id, mode: entry.mode };
  if (entry.mode === "qa") {
    stat.questions = entry.questions.length;
    stat.subs = entry.questions.reduce((t, q) => t + q.subs.length, 0);
    stat.memoed = entry.questions.reduce((t, q) => t + q.subs.filter((s) => typeof s.memo === "string" && s.memo.length > 0).length, 0);
    stat.subsList = entry.questions.flatMap((q) => q.subs.map((s) => q.n + "/" + s.n));
  } else if (entry.mode === "solutions") stat.blocks = entry.blocks.length;
  else if (entry.mode === "solved") { stat.sets = entry.sets.length; stat.subs = entry.sets.reduce((t, s) => t + s.subs.length, 0); }
  else if (entry.mode === "raw") stat.rawChars = entry.text.length;
  else if (entry.mode === "pdf") stat.pages = entry.pages;
  else stat.summaryChars = entry.summary.length;
  stats.push(stat);
}

for (const c of CURATED) {
  const { cap, src } = findSource(c.prefix, c.name);
  const text = src.text || "";
  const summary = src.summary || "";
  const pages = Array.isArray(src.pageImages) ? src.pageImages.length : typeof src.pageImages === "number" ? src.pageImages : 0;
  const base = {
    id: c.id,
    subject: c.subject,
    title: c.title,
    session: c.session,
    kind: c.kind,
    level: c.level,
    pairId: c.pairId || null,
    capture: { file: cap.file, sha256: cap.sha256, sourceName: c.name },
    pages,
    textChars: text.length,
    summaryChars: summary.length,
  };
  let entry;
  if (c.mode === "images") {
    if (text.length > 0) throw new Error(`${c.id}: expected image-only source but text exists`);
    if (!summary) throw new Error(`${c.id}: image-only source has no captured summary`);
    entry = { ...base, mode: "images", summary, note: "Source PDF is page images — NotebookLM's captured summary is shown, not verbatim exam text." };
  } else if (c.mode === "raw") {
    if (text.length === 0) throw new Error(`${c.id}: raw mode requires extracted text`);
    entry = { ...base, mode: "raw", text, note: "Full captured text as extracted — presented verbatim (not parsed into questions)." };
  } else if (c.mode === "solutions") {
    const blocks = parseSolutions(text);
    if (blocks) {
      entry = { ...base, mode: "solutions", blocks, note: `${blocks.length} worked questions with answers parsed from captured text.` };
    } else {
      entry = { ...base, mode: "raw", text, note: "Answer markers not machine-parseable — full captured text shown verbatim." };
    }
  } else if (c.mode === "solved") {
    const sets = parseSolvedSets(text);
    if (sets) {
      entry = { ...base, mode: "solved", sets, note: `Exam + memorandum captured in one source — ${sets.length} set(s) parsed.` };
    } else {
      entry = { ...base, mode: "raw", text, note: "Exam + memorandum source could not be split structurally — full captured text shown verbatim." };
    }
  } else {
    // qa
    const parsed = parseQA(text, { embeddedMemo: !!c.embeddedMemo });
    if (parsed.questions.length > 0 && parsed.subs > 0) {
      for (const q of parsed.questions) for (const s of q.subs) if (s.memo === undefined) s.memo = null;
      entry = { ...base, mode: "qa", questions: parsed.questions, note: `${parsed.questions.length} question block(s), ${parsed.subs} numbered sub-questions parsed from extracted text.` };
      if (parsed.embeddedMemo > 0) {
        entry.embeddedMemo = parsed.embeddedMemo;
        entry.note += ` Captured source also contains its memorandum — ${parsed.embeddedMemo} memo answers joined.`;
      }
      if (parsed.dupes > 0) entry.note += ` ${parsed.dupes} repeated numbering occurrence(s) from PDF column extraction collapsed.`;
    } else if (parsed.questions.length > 0) {
      entry = { ...base, mode: "qa", questions: parsed.questions, note: `${parsed.questions.length} question block(s) parsed (no sub-numbering found).` };
    } else {
      entry = { ...base, mode: "raw", text, note: "Numbered question parse unavailable — full captured text shown verbatim." };
    }
  }
  pushEntry(c, entry, text);
}

// Local downloads (research/Data-QuestionPapers-and-Memos-Downloaded): the
// SOURCE mode is measured, not declared. A text layer tries to parse into a
// qa entry (if the structure will not parse, it stays pdf-mode with an honest
// note — nothing unverified enters the bank); a scan goes through the
// dual-engine OCR gate and either parses to qa or keeps its original file as
// the source of truth (mode "pdf", opened byte-for-byte).
for (const c of LOCAL) {
  const { rel, record } = findLocal(c);
  const base = {
    id: c.id,
    subject: c.subject,
    title: c.title,
    session: c.session,
    kind: c.kind,
    level: c.level,
    pairId: c.pairId || null,
    capture: { file: rel, sha256: record.sha256, sourceName: c.file, local: true },
    pages: record.pages,
    textChars: record.textChars,
    summaryChars: 0,
  };
  if (record.textFile) {
    const text = fs.readFileSync(path.join(LOCAL_CAP_DIR, record.textFile), "utf8");
    const parsed = parseQA(text);
    if (parsed.questions.length > 0 && parsed.subs > 0) {
      for (const q of parsed.questions) for (const s of q.subs) if (s.memo === undefined) s.memo = null;
      const entry = {
        ...base,
        mode: "qa",
        questions: parsed.questions,
        note: `${parsed.questions.length} question block(s), ${parsed.subs} numbered sub-questions parsed from text extracted off the downloaded original (${c.file}); sha256 verified at build time.`,
      };
      if (parsed.dupes > 0) entry.note += ` ${parsed.dupes} repeated numbering occurrence(s) from PDF column extraction collapsed.`;
      pushEntry(c, entry, text);
      continue;
    }
    // text layer present but unparseable: fall back to pdf-mode honestly
    const entry = {
      ...base,
      mode: "pdf",
      note: `Original carries a text layer (${record.textChars} characters) but no question structure parsed from it, so nothing unverified enters the bank. The reader opens the original downloaded file, byte for byte — sha256 ${record.sha256.slice(0, 16)}… verified at build time.`,
    };
    pushEntry(c, entry, "");
    continue;
  }
  {
    if (record.textChars > 40) throw new Error(`${c.id}: no text file in the manifest but a text layer exists (${record.textChars} chars) — rerun scripts/extract_local_text.py`);
    const ocr = ocrByFile.get(rel);
    if (ocrGate(ocr)) {
      const ocrFile = ocr.spacedFile || ocr.rapidFile;
      const text = fs.readFileSync(path.join(LOCAL_CAP_DIR, ocrFile), "utf8");
      const parsed = parseQA(text, { strictHeaders: true });
      let crossFilled = 0;
      if (ocr.winrtFile) {
        const crossText = fs.readFileSync(path.join(LOCAL_CAP_DIR, ocr.winrtFile), "utf8");
        crossFilled = fillFromCross(parsed, parseQA(crossText, { strictHeaders: true }));
      }
      if (parsed.questions.length > 0 && parsed.subs > 0) {
        for (const q of parsed.questions) for (const s of q.subs) if (s.memo === undefined) s.memo = null;
        const entry = {
          ...base,
          textChars: text.length,
          mode: "qa",
          questions: parsed.questions,
          ocr: { parsedFrom: ocrManifest.engines.cross, crossCheck: ocrManifest.engines.primary, cbigramF1: ocr.cbigramF1, digitRunF1: ocr.digitRunF1, pages: ocr.pages },
          note: `Scanned original transcribed by OCR: ${parsed.questions.length} question block(s), ${parsed.subs} numbered sub-questions. Parsed from ${ocrManifest.engines.cross}; independently cross-checked against ${ocrManifest.engines.primary} (character agreement f1=${ocr.cbigramF1}, digit-run agreement f1=${ocr.digitRunF1}). The downloaded PDF stays the source of truth — sha256 ${record.sha256.slice(0, 16)}… verified at build time and openable from this card.`,
        };
        if (crossFilled > 0) entry.note += ` ${crossFilled} sub-text(s) reworded from the cross-check transcription where both engines agreed on content.`;
        if (ocr.spacedRuns && ocr.spacedRuns.repaired > 0) entry.note += ` Word spacing repaired on ${ocr.spacedRuns.repaired} glued run(s) (content-preserving; ${ocr.spacedRuns.rejected} ambiguous run(s) left as transcribed).`;
        if (parsed.dupes > 0) entry.note += ` ${parsed.dupes} repeated numbering occurrence(s) collapsed.`;
        pushEntry(c, entry, text);
        continue;
      }
      // gate passed but structure unparseable: stay pdf, say why (honest)
      const entry = {
        ...base,
        mode: "pdf",
        note: `Scanned PDF: OCR transcription existed (cross-engine cbigram f1=${ocr.cbigramF1}) but no question structure parsed from it, so nothing unverified enters the bank. The reader opens the original downloaded file, byte for byte — sha256 ${record.sha256.slice(0, 16)}… verified at build time.`,
      };
      pushEntry(c, entry, "");
      continue;
    }
    const entry = {
      ...base,
      mode: "pdf",
      note: ocr
        ? `Scanned PDF: extraction found no usable text layer (${record.textChars} characters of page furniture), and the dual-engine OCR cross-check stayed below the honesty bar (character f1=${ocr.cbigramF1 ?? "n/a"}, digit-run f1=${ocr.digitRunF1 ?? "n/a"}) — no transcription enters the bank. The reader opens the original downloaded file, byte for byte — sha256 ${record.sha256.slice(0, 16)}… verified at build time.`
        : `Scanned PDF: extraction found no usable text layer (${record.textChars} characters of page furniture). The reader opens the original downloaded file, byte for byte — sha256 ${record.sha256.slice(0, 16)}… verified at build time.`,
    };
    pushEntry(c, entry, "");
  }
}

// join text-pair memos into their qp entries (verbatim, from the partner capture)
for (const entry of shelf) {
  if (entry.kind !== "qp" || entry.mode !== "qa" || !entry.pairId) continue;
  const partner = shelf.find((p) => p.id === entry.pairId);
  if (!partner || partner.kind !== "memo") continue;
  if (partner.mode === "qa") {
    const memoMap = new Map();
    for (const q of partner.questions) for (const s of q.subs) if (!s.empty) memoMap.set(s.n, s.text);
    let joined = 0;
    for (const q of entry.questions) for (const s of q.subs) {
      if (memoMap.has(s.n)) { s.memo = memoMap.get(s.n); joined++; }
      else s.memo = null;
    }
    entry.joinedMemoSubs = joined;
    entry.note += ` Memo answers joined from ${partner.capture.sourceName} (${joined}/${entry.questions.reduce((t, q) => t + q.subs.length, 0)} sub-answers found).`;
  } else if (partner.mode === "images") {
    entry.note += ` A summary-level memo exists: “${partner.title}” (open the pair from this card).`;
  } else if (partner.mode === "pdf") {
    entry.note += ` A scanned memo exists: “${partner.title}” (open the pair from this card).`;
  }
}
// memo entries of text pairs: mark reverse linkage already via pairId; strip parse noise from memo notes is fine.

// solved sets: join memo subs already inline. Ensure subs without memo are null (not undefined)
for (const entry of shelf) {
  if (entry.mode === "solved") for (const set of entry.sets) for (const s of set.subs) if (s.memo === undefined) s.memo = null;
}

const ids = shelf.map((p) => p.id);
if (new Set(ids).size !== ids.length) throw new Error("duplicate paper ids");

const payload = shelf.map((p) => {
  const out = { ...p };
  if (out.mode !== "raw") delete out.text;
  return out;
});

const lines = [];
lines.push("// AUTO-GENERATED by scripts/extract_papers.mjs — DO NOT EDIT BY HAND.");
lines.push("// Papers & memos shelf: verbatim text parsed from NotebookLM captures and");
lines.push("// from locally downloaded originals (scanned PDFs open byte-for-byte).");
lines.push("// Provenance: every entry cites its source file + manifest sha256.");
lines.push(`export const PAPERS_BUILT_ON = ${JSON.stringify(BUILT_ON)};`);
lines.push("");
lines.push("export const paperShelf = " + JSON.stringify(payload, null, 2) + ";");
lines.push("");
lines.push("export function papersBySubject(subject) {");
lines.push("  return paperShelf.filter((p) => p.subject === subject);");
lines.push("}");
lines.push("");
lines.push("export function paperById(id) {");
lines.push("  return paperShelf.find((p) => p.id === id) || null;");
lines.push("}");
lines.push("");
fs.writeFileSync(OUT, lines.join("\n"), "utf8");

console.log(`wrote ${path.relative(ROOT, OUT)} — ${shelf.length} entries, ${fs.statSync(OUT).size} bytes`);
for (const s of stats) {
  const extra = s.mode === "qa" ? `Q=${s.questions} subs=${s.subs} memoed=${s.memoed} [${(s.subsList || []).join(", ")}]` : s.mode === "solutions" ? `blocks=${s.blocks}` : s.mode === "solved" ? `sets=${s.sets} subs=${s.subs}` : s.mode === "raw" ? `raw=${s.rawChars}` : s.mode === "pdf" ? `pages=${s.pages}` : `summary=${s.summaryChars}`;
  console.log(`  ${s.id.padEnd(24)} ${s.mode.padEnd(9)} ${extra}`);
}
for (const p of shelf.filter((x) => x.joinedMemoSubs !== undefined)) console.log(`  JOIN ${p.id}: ${p.joinedMemoSubs} memo answers`);

export { parseQA, questionStarts, fillFromCross, cbSim };
